-- ==============================================================================
-- ESQUEMA DE BASE DE DATOS PARA SUPABASE (POSTGRESQL) - FUNDO EL CASTILLO
-- ==============================================================================
-- Copia y pega todo este código en el "SQL Editor" de tu proyecto de Supabase
-- y presiona "RUN" para crear todas las tablas, permisos y datos iniciales.

-- 0. TABLA: CAMPAÑAS AGRÍCOLAS (Campaña 2025, 2026, etc.)
CREATE TABLE IF NOT EXISTS campanas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    anio INTEGER NOT NULL,
    activa BOOLEAN DEFAULT FALSE,
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1. TABLA: PARCELAS Y ARRIENDOS (3 Hectáreas)
CREATE TABLE IF NOT EXISTS parcelas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    hectareas NUMERIC(6,2) NOT NULL DEFAULT 0,
    tipo_tenencia TEXT DEFAULT 'Alquilado', -- 'Alquilado' o 'Propio'
    propietario TEXT,
    costo_alquiler_mensual NUMERIC(10,2) DEFAULT 0,
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABLA: CULTIVOS Y VARIEDADES (Palta Hass, Fuerte, Plátano, etc.)
CREATE TABLE IF NOT EXISTS variedades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    especie TEXT NOT NULL,
    num_arboles INTEGER DEFAULT 0,
    anio_plantacion INTEGER,
    hectareas NUMERIC(6,2) DEFAULT 0,
    parcela_id BIGINT REFERENCES parcelas(id) ON DELETE SET NULL,
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABLA: INSUMOS Y PRODUCTOS QUÍMICOS / ALMACÉN
CREATE TABLE IF NOT EXISTS productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    categoria TEXT DEFAULT 'Fertilizante / Fitosanitario',
    unidad TEXT DEFAULT 'Kg/L',
    stock_anterior NUMERIC(10,2) DEFAULT 0,
    stock_actual NUMERIC(10,2) DEFAULT 0,
    precio_referencial NUMERIC(10,2) DEFAULT 0,
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TABLA: COMPRAS DE INSUMOS
CREATE TABLE IF NOT EXISTS compras_productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    producto_id BIGINT NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
    cantidad NUMERIC(10,2) NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL,
    total NUMERIC(10,2) NOT NULL,
    proveedor TEXT,
    nro_factura TEXT,
    nro_albaran TEXT,
    pagado BOOLEAN DEFAULT TRUE,
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. TABLA: TRATAMIENTOS Y APLICACIONES EN CAMPO
CREATE TABLE IF NOT EXISTS tratamientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    variedad_id BIGINT NOT NULL REFERENCES variedades(id) ON DELETE RESTRICT,
    producto_id BIGINT NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
    cantidad NUMERIC(10,2) NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL,
    total NUMERIC(10,2) NOT NULL,
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. TABLA: VENTAS DE COSECHA
CREATE TABLE IF NOT EXISTS ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    variedad_id BIGINT NOT NULL REFERENCES variedades(id) ON DELETE RESTRICT,
    kilos NUMERIC(10,2) NOT NULL,
    precio_kilo NUMERIC(10,2) NOT NULL,
    total NUMERIC(10,2) NOT NULL,
    comprador TEXT,
    nro_boleta TEXT,
    nro_factura TEXT,
    cobrado BOOLEAN DEFAULT TRUE,
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. TABLA: INGRESOS FINANCIEROS Y OTROS
CREATE TABLE IF NOT EXISTS ingresos_financieros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    concepto TEXT NOT NULL,
    total NUMERIC(10,2) NOT NULL,
    pagador TEXT,
    nro_factura TEXT,
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. TABLA: GASTOS ESPECÍFICOS POR CULTIVO
CREATE TABLE IF NOT EXISTS gastos_especificos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    concepto TEXT NOT NULL,
    total NUMERIC(10,2) NOT NULL,
    empresa TEXT,
    nro_factura TEXT,
    variedad_id BIGINT REFERENCES variedades(id) ON DELETE SET NULL,
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. TABLA: GASTOS GENERALES Y ARRIENDOS DEL CAMPO
CREATE TABLE IF NOT EXISTS gastos_generales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    concepto TEXT NOT NULL,
    total NUMERIC(10,2) NOT NULL,
    empresa TEXT,
    nro_factura TEXT,
    categoria TEXT DEFAULT 'Mantenimiento / Operación',
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. TABLA: TRABAJADORES (PERSONAL)
CREATE TABLE IF NOT EXISTS trabajadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    telefono TEXT,
    rol TEXT DEFAULT 'Jornalero',
    costo_hora_defecto NUMERIC(10,2) DEFAULT 10.0,
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 11. TABLA: JORNALES DE TRABAJO DIARIO
CREATE TABLE IF NOT EXISTS jornales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    trabajador_id BIGINT NOT NULL REFERENCES trabajadores(id) ON DELETE CASCADE,
    variedad_id BIGINT REFERENCES variedades(id) ON DELETE SET NULL,
    horas NUMERIC(6,2) NOT NULL,
    precio_hora NUMERIC(10,2) NOT NULL,
    total NUMERIC(10,2) NOT NULL,
    labor TEXT,
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- POLÍTICAS DE ACCESO (ROW LEVEL SECURITY)
-- Permite lectura y escritura pública para el cliente web de GitHub Pages con anon_key
-- ==============================================================================
ALTER TABLE campanas ENABLE ROW LEVEL SECURITY;
ALTER TABLE parcelas ENABLE ROW LEVEL SECURITY;
ALTER TABLE variedades ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE compras_productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE tratamientos ENABLE ROW LEVEL SECURITY;
ALTER TABLE ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE ingresos_financieros ENABLE ROW LEVEL SECURITY;
ALTER TABLE gastos_especificos ENABLE ROW LEVEL SECURITY;
ALTER TABLE gastos_generales ENABLE ROW LEVEL SECURITY;
ALTER TABLE trabajadores ENABLE ROW LEVEL SECURITY;
ALTER TABLE jornales ENABLE ROW LEVEL SECURITY;

DO $$ 
DECLARE
    tbl text;
BEGIN
    FOR tbl IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Acceso publico %I" ON %I;', tbl, tbl);
        EXECUTE format('CREATE POLICY "Acceso publico %I" ON %I FOR ALL USING (true) WITH CHECK (true);', tbl, tbl);
    END LOOP;
END $$;

-- ==============================================================================
-- DATOS INICIALES DE FUNDO EL CASTILLO
-- ==============================================================================

-- 0. Campañas Agrícolas
INSERT INTO campanas (nombre, anio, activa, notas)
VALUES
    ('Campaña 2026', 2026, TRUE, 'Campaña agrícola principal en curso'),
    ('Campaña 2025', 2025, FALSE, 'Campaña agrícola anterior')
ON CONFLICT (nombre) DO NOTHING;

-- 1. Arriendos de las 3 Hectáreas
INSERT INTO parcelas (nombre, hectareas, tipo_tenencia, propietario, notas)
VALUES
    ('Lote 1 (2 Ha)', 2.0, 'Alquilado', 'Propietario 1', 'Arriendo de 2 hectáreas'),
    ('Lote 2 (1 Ha)', 1.0, 'Alquilado', 'Propietario 2', 'Arriendo de 1 hectárea')
ON CONFLICT DO NOTHING;

-- 2. Variedades y Árboles (Plantas iniciales en 0 por definir por el usuario)
INSERT INTO variedades (nombre, especie, num_arboles, anio_plantacion, hectareas, notas)
VALUES
    ('PALTA FUERTE 1', 'Palta Fuerte', 0, 2009, 0.4, 'Plantación año 2009 en alta producción'),
    ('PALTA FUERTE 2', 'Palta Fuerte', 0, 2023, 0.6, 'Plantación año 2023 en desarrollo'),
    ('PALTA HASS', 'Palta Hass', 0, 2010, 2.0, '2 hectáreas de Palta Hass'),
    ('PLATANO', 'Plátano', 0, NULL, 1.0, '1 hectárea de cultivo de plátano'),
    ('FRUTALES VARIOS', 'Frutales Varios', 0, NULL, 0.2, 'Cítricos y frutales diversos')
ON CONFLICT (nombre) DO NOTHING;

-- 3. Trabajadores iniciales
INSERT INTO trabajadores (nombre, rol, costo_hora_defecto)
VALUES
    ('Mauro Robles', 'Jornalero / Operador', 10.0),
    ('Kike', 'Jornalero / Poda y Riego', 10.0),
    ('Trabajador de Apoyo', 'Jornalero Temporal', 10.0)
ON CONFLICT (nombre) DO NOTHING;

-- 4. Registro histórico de gasto general (del Excel: Movimiento de tierra a caballo S/. 220)
INSERT INTO gastos_generales (fecha, concepto, total, empresa, categoria, notas)
VALUES ('2026-03-18', 'MOVIMIENTO DE TIERRA A CABALLO', 220.0, 'Servicio Local', 'Preparación de Suelos', 'Registro inicial migrado de plantilla Excel')
ON CONFLICT DO NOTHING;

-- 5. Catálogo de 45 productos fitosanitarios y fertilizantes
INSERT INTO productos (nombre, categoria, unidad, stock_anterior, stock_actual, precio_referencial)
VALUES
    ('ABONO FOLIAR', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('ABONO ORGANICO', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('ACEITE AGRICOLA (FGA)', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('ACIDO FOLICO', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('ADHERENTE SILICONADO', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('AKRON', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('ALGAS MARINAS', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('SULFATO DE AMONIO', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('AMINOACIDOS', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('AZUFRE', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('BIOL', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('BORO', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('CAL OMEX', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('CALCIO BORO ZINC', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('CARBENDAZINA', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('CICLON', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('CITOQUININA', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('JABON POTASICO', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('EMAMECTIN BENZOATO', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('ACETAMIPRID', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('ENRAIZADOR', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('ERAIZER', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('FOSFATO DIAMONICO', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('FOSFORO', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('MELAZA', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('METOMIL', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('MICROELEMENTOS', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('NITRATO DE AMONIO', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('OLIGOMIX', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('PERMETRINA', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('SULFATO DE COBRE', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('SULFATO DE COBRE GRANULADO', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('SULFATO DE POTASIO', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('TIFON', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('YESO AGRICOLA', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('SANIX', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('ZINC', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('ABONO 20 20 20', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('SILICIO', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('PIRIMETANIL', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('BACILLUS', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('STIMULATE', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('VIGOR PHOS', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('REGULADOR PH', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0),
    ('TABACAZO', 'Insumo Fitosanitario / Fertilizante', 'Kg/L', 0, 0, 0)
ON CONFLICT (nombre) DO NOTHING;
